---

server:
    install: '1'
    timezone: Europe/London
    locale: en_GB.UTF-8
    packages: [python-pip]
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: phansible-firstgo, ip: 192.168.33.99, memory: '512', sharedfolder: ./, syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
composer:
    install: '1'
owncloud:
    admin_user: "{{ vault_owncloud_admin_user }}"
    admin_password: "{{ vault_owncloud_admin_password }}"
    user: "{{ vault_owncloud_user }}"
    password: "{{ vault_owncloud_password }}"
aws_output_format: 'json'
aws_region: 'eu-west-1'
aws_cli_profile_name: 'backupprofile'
