---

- name: set explicit ServerName for default website
  become: yes
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: ServerName
    line: ServerName {{ apache_servername }}

- name: get certbot
  become: yes
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/sbin
    mode: a+x

- name: install certificate
  command: certbot-auto --non-interactive {{ cert.additional_flags }} --agree-tos --email {{ cert.email_address }} --apache --domains {{ apache_servername }}

- name: set up cert renewal cron job
  cron:
    hour: 0,12 # midnight and midday
    minute: 0 # run on minute zero
    name: ssl certificate renewal
    user: "{{ my_remote_user }}"
    # sleep for a random number of minutes before renewing cert
    job: sleep $(shuf -i 0-59 -n 1)m; certbot-auto renew {{ cert.additional_flags }} --no-self-upgrade --quiet
