---

- name: install ansible
  apt:
    name: ansible
  become: yes

- name: create local dir to work from
  file:
    path: "{{workdir}}"
    state: directory
    owner: "{{ cron_user }}"
    group: "{{ remote_user }}"
    mode: 0751

- name: Create crontab entry to clone/pull git repository
  template:
    src: etc_cron.d_ansible-pull.j2
    dest: /etc/cron.d/ansible-pull
    owner: "{{ cron_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Create logrotate entry for ansible-pull.log
  template:
    src: etc_logrotate.d_ansible-pull.j2
    dest: /etc/logrotate.d/ansible-pull
    owner: "{{ cron_user }}"
    group: "{{ remote_user }}"
    mode: 0644
