---

- name: put owncloud into maintenance mode
  become: yes
  become_user: www-data
  command: php occ maintenance:mode --on
  args:
    chdir: /var/www/owncloud/

- name: stop apache
  become: yes
  service:
    name: apache2
    state: stopped

- name: get filename of latest backup from aws
  shell: aws s3 ls s3://discopatrick-owncloud-backups/ | awk '{print $4}' | grep 'owncloud-backup-.*\.tar\.gz' | sort | tail -n 1
  register: backup_filename

- name: copy backup file to home folder
  command: aws s3 cp s3://discopatrick-owncloud-backups/{{ backup_filename.stdout }} ~/

# - name: move backup file to owncloud folder
#   become: yes
#   copy:
#     remote_src: yes
#     src: /home/{{ my_remote_user }}/{{ backup_filename.stdout }}
#     dest: /var/www/owncloud/owncloud-backup.tar.gz
#     owner: www-data
#     group: www-data

- name: create temp backup directory
  file:
    state: directory
    path: ~/backup_temp_dir/

- name: unpack the backup
  unarchive:
    copy: no
    src: ~/{{ backup_filename.stdout }}
    dest: ~/backup_temp_dir/
    list_files: yes

- name: import sql dump
  # must use 'shell' module, as the command uses the '<' character
  shell: mysql --host=localhost --user={{ mysql.user }} --password={{ mysql.password }} {{ mysql.database }} <  ~/backup_temp_dir/owncloud.sql

- name: sync the config folder
  become: yes
  synchronize:
    src: /home/{{ my_remote_user }}/backup_temp_dir/config
    dest: /var/www/owncloud/
    recursive: yes
    delete: yes
  delegate_to: 192.168.33.99

- name: sync the data folder
  become: yes
  synchronize:
    src: /home/{{ my_remote_user }}/backup_temp_dir/data
    dest: /var/www/owncloud/
    delete: yes
  delegate_to: 192.168.33.99

- name: delete the temp folder
  file:
    state: absent
    path: ~/backup_temp_dir/

- name: delete the backup file
  file:
    state: absent
    path: ~/{{ backup_filename.stdout }}

- name: run the owncloud permissions script
  become: yes
  script: ./files/owncloud_permissions.sh

- name: start apache
  become: yes
  service:
    name: apache2
    state: started

- name: take owncloud out of maintenance mode
  become: yes
  become_user: www-data
  command: php occ maintenance:mode --off
  args:
    chdir: /var/www/owncloud/
