---

my_remote_user: admin

mysql:
  root_password: "{{ vault_mysql_root_password }}"
  user: "{{ vault_mysql_user }}" # must be no longer than 16 chars
  password: "{{ vault_mysql_password }}"
  dump: ''

aws:
  bucket_name: "{{ vault_aws.bucket_name }}"
  backup_access_key_id: "{{ vault_aws.backup_access_key_id }}"
  backup_secret_access_key: "{{ vault_aws.backup_secret_access_key }}"
  restore_access_key_id: "{{ vault_aws.restore_access_key_id }}"
  restore_secret_access_key: "{{ vault_aws.restore_secret_access_key }}"

domain_name: "{{ vault_domain_name }}"
protocol: https
