---
- name: put owncloud into maintenance mode
  become: yes
  become_user: www-data
  command: php occ maintenance:mode --on
  args:
    chdir: /var/www/owncloud/

- name: stop apache
  become: yes
  service:
    name: apache2
    state: stopped

- name: get server isodatetime
  command: date --iso-8601=seconds --utc
  register: isodatetime

- name: get epoch datetime
  command: date +%s
  register: epochdatetime

- name: create temp backup directory
  file:
    state: directory
    path: ~/owncloud-backup-{{ epochdatetime.stdout }}

- name: dump the db
  mysql_db: name={{ mysql_database }} state=dump target=~/owncloud-backup-{{ epochdatetime.stdout }}/owncloud.sql

- name: copy config folder
  synchronize:
    src: /var/www/owncloud/config
    dest: /home/{{ my_remote_user }}/owncloud-backup-{{ epochdatetime.stdout }}/
    owner: no
    group: no
  delegate_to: "{{ inventory_hostname }}" # both src and dest are on the current host in context
  when: "'-pull' not in inventory_hostname"

- name: copy data folder
  synchronize:
    src: /var/www/owncloud/data
    dest: /home/{{ my_remote_user }}/owncloud-backup-{{ epochdatetime.stdout }}/
    owner: no
    group: no
  delegate_to: "{{ inventory_hostname }}" # both src and dest are on the current host in context
  when: "'-pull' not in inventory_hostname"

- name: tar and gzip
  # has to be shell to work - best guess is that chdir doesn't work with command... although I think I've used it elsewhere...
  shell: tar -czvf ./owncloud-backup-{{ isodatetime.stdout }}.tar.gz ./*
  args:
    chdir: ~/owncloud-backup-{{ epochdatetime.stdout }}

- name: copy backup to aws
  command: "aws s3 cp ./owncloud-backup-{{ isodatetime.stdout }}.tar.gz s3://{{ aws.bucket_name }}/ --profile {{ aws_cli_profile_name }}"
  args:
    chdir: ~/owncloud-backup-{{ epochdatetime.stdout }}

- name: delete the backup folder
  file:
    state: absent
    path: ~/owncloud-backup-{{ epochdatetime.stdout }}

- name: start apache
  become: yes
  service:
    name: apache2
    state: started

- name: take owncloud out of maintenance mode
  become: yes
  become_user: www-data
  command: php occ maintenance:mode --off
  args:
    chdir: /var/www/owncloud/
