---
- name: put owncloud into maintenance mode
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ maintenance:mode --on
  args:
    chdir: /var/www/owncloud/

- name: take owncloud out of maintenance mode
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ maintenance:mode --off
  args:
    chdir: /var/www/owncloud/