---
server:
    install: '1'
    timezone: Europe/London
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: phansible-firstgo, ip: 192.168.33.99, memory: '512', sharedfolder: ./, syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
composer:
    install: '1'
owncloud:
    user: admin
    password: Admin123!
