---
# application tasks to be customized and to run after the main provision

- name: add vagrant user to www-data group
  user:
    name: vagrant
    groups: www-data
    append: yes

- name: add owncloud apt key
  apt_key:
   url: https://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/Release.key
   validate_certs: no # this is insecure and must be fixed

- name: add owncloud repo to apt
  apt_repository:
    repo: 'deb http://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/ /'
    update_cache: yes

- name: install owncloud
  apt:
    name: owncloud

- name: change ownership of the owncloud directory
  file:
    state: directory
    path: /var/www/owncloud/
    owner: www-data
    group: www-data

# the occ is the owncloud command line interface

- name: get list of available occ tasks
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ list
  args:
    chdir: /var/www/owncloud/
  register: occ_list

- name: run owncloud cli installer (only if 'maintenance:install' task is available)
  become: yes
  become_method: sudo
  become_user: www-data
  command: 'php occ maintenance:install --database "mysql" --database-name "{{ mysql.database }}"  --database-user "{{ mysql.user }}" --database-pass "{{ mysql.password }}" --admin-user "{{ owncloud.user }}" --admin-pass "{{ owncloud.password }}"'
  args:
    chdir: /var/www/owncloud/
  when: occ_list.stdout.find('maintenance:install') != -1

- name: configure occ to use correct domain name # must happen after install
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ config:system:set overwrite.cli.url --value "http://192.168.33.99/owncloud"
  args:
    chdir: /var/www/owncloud/

- name: configure owncloud with correct RewriteBase
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ config:system:set htaccess.RewriteBase --value "/owncloud"
  args:
    chdir: /var/www/owncloud/

- name: update .htaccess with correct RewriteBase
  # should be replaced in 9.0.3 with: php occ maintenance:update:htaccess
  lineinfile:
    dest: /var/www/owncloud/.htaccess
    regexp: ^\s*RewriteBase
    line: RewriteBase /owncloud

# todo: this attempt at idempotency for the 'add our domain/ip' task does not work.
# however, no errors are caused, so it's fine for now.

# - name: get current trusted_domains config
#   become: yes
#   become_method: sudo
#   become_user: www-data
#   command: php occ config:system:get trusted_domains
#   args:
#     chdir: /var/www/owncloud/
#   register: trusted_domains

- name: add our domain/ip to the list of trusted_domains # (only if not already there)
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ config:system:set trusted_domains 1 --value=192.168.33.99
  args:
    chdir: /var/www/owncloud/
  # when: trusted_domains.stdout.find('192.168.33.99') != -1

- name: get 'lastseen' status of patrick user
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ user:lastseen patrick
  args:
    chdir: /var/www/owncloud/
  register: lastseen

- name: add a user
  become: yes
  become_method: sudo
  become_user: www-data
  environment:
    OC_PASS: Patrick123!
  command: php occ user:add --password-from-env patrick
  args:
    chdir: /var/www/owncloud/
  when: lastseen.stdout.find('User does not exist') != -1

- name: check if contacts dir exists
  stat: 
    path: /var/www/owncloud/apps/contacts
  register: contacts_app_dir

- name: get contacts app
  become: yes
  become_method: sudo
  become_user: www-data
  get_url:
    url: https://github.com/owncloud/contacts/releases/download/v0.0.0.59/contacts.tar.gz
    dest: /var/www/owncloud/apps/
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: unpack contacts app
  become: yes
  become_method: sudo
  become_user: www-data
  unarchive:
    copy: no
    src: /var/www/owncloud/apps/contacts.tar.gz
    dest: /var/www/owncloud/apps/
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: remove contacts app tarball
  become: yes
  become_method: sudo
  become_user: www-data
  file:
    path: /var/www/owncloud/apps/contacts.tar.gz
    state: absent
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: enable the contacts app
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ app:enable contacts
  args:
    chdir: /var/www/owncloud/  

- name: run the owncloud permissions script # do this after all apps are added
  script: ./files/owncloud_permissions.sh

- name: enable required apache modules
  apache2_module:
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: create apache conf file
  become: yes
  template:
    src: owncloud.conf.tpl
    dest: /etc/apache2/sites-available/owncloud.conf
  notify: restart apache

- name: symlink apache conf file to enable site
  file:
    src: /etc/apache2/sites-available/owncloud.conf
    dest: /etc/apache2/sites-enabled/owncloud.conf
    state: link
  notify: restart apache

- name: 'Install AWS CLI'
  tags: 'aws-cli'
  become: yes
  pip:
    name: awscli
    state: latest

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  become: no
  file: >
    path=~/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  become: no
  template: >
    src=aws_cli_config.j2
    dest=~/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644

