---
# application tasks to be customized and to run after the main provision

- name: add owncloud apt key
  apt_key:
   url: https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/Release.key
   validate_certs: no

- name: add owncloud repo to apt
  apt_repository:
    repo: 'deb http://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/ /'
    update_cache: yes

- name: install owncloud
  apt:
    name: owncloud

- name: change ownership of the owncloud directory
  file:
    state: directory
    path: /var/www/owncloud/
    owner: www-data
    group: www-data

- name: run owncloud cli installer
  become: yes
  become_method: sudo
  become_user: www-data
  command: 'php occ maintenance:install --database "mysql" --database-name "{{ mysql.database }}"  --database-user "{{ mysql.user }}" --database-pass "{{ mysql.password }}" --admin-user "{{ owncloud.user }}" --admin-pass "{{ owncloud.password }}"'
  args:
    chdir: /var/www/owncloud/
