---
# application tasks to be customized and to run after the main provision

- name: add owncloud apt key
  apt_key:
   url: https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/Release.key
   validate_certs: no
