---
# application tasks to be customized and to run after the main provision

- name: add owncloud apt key
  apt_key:
   url: https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/Release.key
   validate_certs: no

- name: add owncloud repo to apt
  apt_repository:
    repo: 'deb http://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/ /'
    update_cache: yes

- name: install owncloud
  apt:
    name: owncloud

- name: change ownership of owncloud files
  file:
    state: directory
    recurse: yes
    path: /usr/share/owncloud/
    owner: www-data
    group: www-data
    mode: 0644

- name: create apache conf file
  sudo: yes
  template:
    src: owncloud.conf.tpl
    dest: /etc/apache2/sites-available/owncloud.conf
  notify: restart apache

- name: symlink apache conf file to enable site
  file:
    src: /etc/apache2/sites-available/owncloud.conf
    dest: /etc/apache2/sites-enabled/owncloud.conf
    state: link
  notify: restart apache
