---
# application tasks to be customized and to run after the main provision

- name: Download ownCloud
  get_url:
    url: https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/Release.key
    dest: ~/Release.key
    validate_certs: no
