---
# application tasks to be customized and to run after the main provision

- name: add remote user to www-data group
  become: yes
  user:
    name: "{{ my_remote_user }}"
    groups: www-data
    append: yes

- name: add owncloud apt key
  become: yes
  apt_key:
   url: https://download.owncloud.org/download/repositories/9.0.3/xUbuntu_14.04/Release.key
   validate_certs: no # this is insecure and must be fixed

- name: add owncloud repo to apt
  become: yes
  apt_repository:
    repo: 'deb http://download.owncloud.org/download/repositories/9.0.3/xUbuntu_14.04/ /'
    update_cache: yes

- name: stop apache to prevent front-end install
  service:
    name: apache2
    state: stopped
  notify: restart apache

- name: install owncloud
  become: yes
  apt:
    name: owncloud

- name: change ownership of the owncloud directory
  become: yes
  file:
    state: directory
    path: /var/www/owncloud/
    owner: www-data
    group: www-data

# the occ is the owncloud command line interface

- name: get list of available occ tasks
  become: yes
  become_user: www-data
  command: php occ list
  args:
    chdir: /var/www/owncloud/
  register: occ_list

- name: run owncloud cli installer (only if 'maintenance:install' task is available)
  become: yes
  become_user: www-data
  command: 'php occ maintenance:install --database "mysql" --database-name "{{ mysql_database }}"  --database-user "{{ mysql.user }}" --database-pass "{{ mysql.password }}" --admin-user "{{ owncloud.admin_user }}" --admin-pass "{{ owncloud.admin_password }}"'
  args:
    chdir: /var/www/owncloud/
  when: occ_list.stdout.find('maintenance:install') != -1

- name: disable update checker
  become: yes
  become_user: www-data
  command: php occ config:system:set updatechecker --value false
  args:
    chdir: /var/www/owncloud/

- name: disable update notification app
  become: yes
  become_user: www-data
  command: php occ app:disable updatenotification
  args:
    chdir: /var/www/owncloud/

- name: configure occ to use correct domain name # must happen after install
  become: yes
  become_user: www-data
  command: php occ config:system:set overwrite.cli.url --value "http://{{ inventory_hostname }}/owncloud"
  args:
    chdir: /var/www/owncloud/

- name: configure owncloud with correct RewriteBase
  become: yes
  become_user: www-data
  command: php occ config:system:set htaccess.RewriteBase --value "/owncloud"
  args:
    chdir: /var/www/owncloud/

- name: update .htaccess with correct RewriteBase
  # should be replaced in 9.0.3 with: php occ maintenance:update:htaccess
  become: yes
  become_user: www-data
  lineinfile:
    dest: /var/www/owncloud/.htaccess
    regexp: ^\s*RewriteBase
    line: RewriteBase /owncloud

# todo: this attempt at idempotency for the 'add our domain/ip' task does not work.
# however, no errors are caused, so it's fine for now.

# - name: get current trusted_domains config
#   become: yes
#   become_method: sudo
#   become_user: www-data
#   command: php occ config:system:get trusted_domains
#   args:
#     chdir: /var/www/owncloud/
#   register: trusted_domains

- name: add our domain/ip to the list of trusted_domains # (only if not already there)
  become: yes
  become_user: www-data
  command: php occ config:system:set trusted_domains 1 --value={{ inventory_hostname }}
  args:
    chdir: /var/www/owncloud/
  # when: trusted_domains.stdout.find('192.168.33.99') != -1

- name: get 'lastseen' status of  user
  become: yes
  become_user: www-data
  command: php occ user:lastseen {{ owncloud.user }}
  args:
    chdir: /var/www/owncloud/
  register: lastseen

- name: add a user
  become: yes
  become_user: www-data
  environment:
    OC_PASS: "{{ owncloud.password }}"
  command: php occ user:add --password-from-env {{ owncloud.user }}
  args:
    chdir: /var/www/owncloud/
  when: lastseen.stdout.find('User does not exist') != -1

- name: check if contacts dir exists
  become: yes
  stat: 
    path: /var/www/owncloud/apps/contacts
  register: contacts_app_dir

- name: check if calendar dir exists
  become: yes
  stat: 
    path: /var/www/owncloud/apps/calendar
  register: calendar_app_dir

## TODO: combine the following get_url and unarchive pairs into single tasks?

- name: get contacts app
  become: yes
  # become_user: www-data
  get_url:
    url: https://github.com/owncloud/contacts/releases/download/v0.0.0.59/contacts.tar.gz
    dest: /var/www/owncloud/apps/
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: get calendar app
  become: yes
  # become_user: www-data
  get_url:
    url: https://github.com/owncloud/calendar/releases/download/v1.2.2/calendar.tar.gz
    dest: /var/www/owncloud/apps/
  when: calendar_app_dir.stat.exists is defined and calendar_app_dir.stat.exists == False

- name: unpack contacts app
  become: yes
  # become_user: www-data
  unarchive:
    copy: no
    src: /var/www/owncloud/apps/contacts.tar.gz
    dest: /var/www/owncloud/apps/
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: unpack calendar app
  become: yes
  # become_user: www-data
  unarchive:
    copy: no
    src: /var/www/owncloud/apps/calendar.tar.gz
    dest: /var/www/owncloud/apps/
  when: calendar_app_dir.stat.exists is defined and calendar_app_dir.stat.exists == False

- name: remove contacts app tarball
  become: yes
  # become_user: www-data
  file:
    path: /var/www/owncloud/apps/contacts.tar.gz
    state: absent
  when: contacts_app_dir.stat.exists is defined and contacts_app_dir.stat.exists == False

- name: remove calendar app tarball
  become: yes
  # become_user: www-data
  file:
    path: /var/www/owncloud/apps/calendar.tar.gz
    state: absent
  when: calendar_app_dir.stat.exists is defined and calendar_app_dir.stat.exists == False

- name: enable the contacts app
  become: yes
  become_user: www-data
  command: php occ app:enable contacts
  args:
    chdir: /var/www/owncloud/  

- name: enable the calendar app
  become: yes
  become_user: www-data
  command: php occ app:enable calendar
  args:
    chdir: /var/www/owncloud/

- name: run the owncloud permissions script # do this after all apps are added
  become: yes
  script: ./files/owncloud_permissions.sh

- name: enable required apache modules
  apache2_module:
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: create apache conf file
  become: yes
  template:
    src: owncloud.conf.tpl
    dest: /etc/apache2/sites-available/owncloud.conf
  notify: restart apache

- name: symlink apache conf file to enable site
  become: yes
  file:
    src: /etc/apache2/sites-available/owncloud.conf
    dest: /etc/apache2/sites-enabled/owncloud.conf
    state: link
  notify: restart apache

- name: 'Install AWS CLI'
  tags: 'aws-cli'
  become: yes
  pip:
    name: awscli
    state: latest

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  file: >
    path=~/.aws
    state=directory
    owner={{ my_remote_user }}
    group={{ my_remote_user }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  template: >
    src=aws_cli_config.j2
    dest=~/.aws/config
    owner={{ my_remote_user }}
    group={{ my_remote_user }}
    mode=0600
