---
# application tasks to be customized and to run after the main provision

- name: add owncloud apt key
  apt_key:
   url: https://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/Release.key
   validate_certs: no # this is insecure and must be fixed

- name: add owncloud repo to apt
  apt_repository:
    repo: 'deb http://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/ /'
    update_cache: yes

- name: install owncloud
  apt:
    name: owncloud

- name: change ownership of the owncloud directory
  file:
    state: directory
    path: /var/www/owncloud/
    owner: www-data
    group: www-data

- name: run the owncloud permissions script
  script: ./files/owncloud_permissions.sh

# the occ is the owncloud command line interface

- name: get list of available occ tasks
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ list
  args:
    chdir: /var/www/owncloud/
  register: occ_list

- name: run owncloud cli installer (only if 'maintenance:install' task is available)
  become: yes
  become_method: sudo
  become_user: www-data
  command: 'php occ maintenance:install --database "mysql" --database-name "{{ mysql.database }}"  --database-user "{{ mysql.user }}" --database-pass "{{ mysql.password }}" --admin-user "{{ owncloud.user }}" --admin-pass "{{ owncloud.password }}"'
  args:
    chdir: /var/www/owncloud/
  when: occ_list.stdout.find('maintenance:install') != -1

# todo: this attempt at idempotency for the 'add our domain/ip' task does not work.
# however, no errors are caused, so it's fine for now.

# - name: get current trusted_domains config
#   become: yes
#   become_method: sudo
#   become_user: www-data
#   command: php occ config:system:get trusted_domains
#   args:
#     chdir: /var/www/owncloud/
#   register: trusted_domains

- name: add our domain/ip to the list of trusted_domains # (only if not already there)
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ config:system:set trusted_domains 1 --value=192.168.33.99
  args:
    chdir: /var/www/owncloud/
  # when: trusted_domains.stdout.find('192.168.33.99') != -1

- name: get 'lastseen' status of patrick user
  become: yes
  become_method: sudo
  become_user: www-data
  command: php occ user:lastseen patrick
  args:
    chdir: /var/www/owncloud/
  register: lastseen

- name: add a user
  become: yes
  become_method: sudo
  become_user: www-data
  environment:
    OC_PASS: Patrick123!
  command: php occ user:add --password-from-env patrick
  args:
    chdir: /var/www/owncloud/
  when: lastseen.stdout.find('User does not exist') != -1

- name: enable required apache modules
  apache2_module:
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: create apache conf file
  sudo: yes
  template:
    src: owncloud.conf.tpl
    dest: /etc/apache2/sites-available/owncloud.conf
  notify: restart apache

- name: symlink apache conf file to enable site
  file:
    src: /etc/apache2/sites-available/owncloud.conf
    dest: /etc/apache2/sites-enabled/owncloud.conf
    state: link
  notify: restart apache
