---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - php
    - composer
    - { role: app, tags: ['app'] }
