---
- hosts: all
  become: no
  become_method: sudo
  become_user: root
  vars_files:
    - group_vars/vault.yml
  roles:
    - server
    - { role: vagrant_local, when: "'dev' in group_names" }
    - apache
    - mysql
    - php
    - composer
    - { role: admin_user, when: "'dev' not in group_names" }
    - { role: app, tags: ['app'] }
