---
- name: provision the server for OwnCloud
  hosts: all
  gather_facts: no
  become: no
  become_method: sudo
  become_user: root
  remote_user: "{{ my_remote_user }}"
  roles:
    - { role: admin_user, when: "'dev' not in group_names" }
    - server
    - { role: vagrant_local, when: "'dev' in group_names" }
    - apache
    - mysql
    - php
    - composer
    - { role: app, tags: ['app'] }
    - { role: cron, tags: ['cron']}
