---
- hosts: all
  become: no
  become_method: sudo
  become_user: root
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - php
    - composer
    - { role: app, tags: ['app'] }
