---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - php
    - composer
    - ssilab.aws-cli
    - { role: app, tags: ['app'] }
