---

- name: create admin group
  remote_user: "{{ admin_user_role_remote_user }}"
  group:
    name: admin

- name: Allow admin group to have passwordless sudo
  remote_user: "{{ admin_user_role_remote_user }}"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: create admin user in admin group
  remote_user: "{{ admin_user_role_remote_user }}"
  user:
    name: admin
    groups: admin
    append: yes
    shell: /bin/bash

- name: add ssh public key for admin user
  remote_user: "{{ admin_user_role_remote_user }}"
  authorized_key:
    user: admin
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
