---

- name: create admin group
  group:
    name: admin

- name: Allow admin group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: create admin user in admin group
  become: yes
  user:
    name: admin
    groups: admin
    append: yes
