# schedule is fed directly to cron
schedule: '*/5 * * * *'

# User to run ansible-pull as from cron
cron_user: "{{ remote_user }}"

# File that ansible will use for logs
logfile: /var/log/ansible-pull.log

# Directory to where repository will be cloned
workdir: /var/lib/ansible/local

# Repository to check out -- YOU MUST CHANGE THIS
# repo must contain a local.yml file at top level
#repo_url: git://github.com/sfromm/ansible-playbooks.git
repo_url: SUPPLY_YOUR_OWN_GIT_URL_HERE

repo_branch: feature/cron_backup
