# File that ansible will use for logs
logfile: /var/log/ansible-pull.log

# Directory to where repository will be cloned
workdir: /var/lib/ansible/local

repo_url: git://github.com/discopatrick/owncloud-ansible.git

repo_branch: feature/cron_backup
